name: Main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/synocommunity/spksrc
    name: Release
    steps:
      - name: Get latest cloudflared version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: cloudflare/cloudflared
          releases-only: true
        id: cloudflared-version
      
      - run: echo "cloudflared is at version ${{ steps.cloudflared-version.outputs.tag }}"

      - name: Get latest built version
        uses: oprypin/find-latest-tag@v1
        continue-on-error: true
        with:
          repository: paulgit/syno-cloudflared-builds
          releases-only: true
        id: syno-cloudflared-version
      
      - run: echo "syno-cloudflared is at version ${{ steps.syno-cloudflared-version.outputs.tag }}"

      - name: Pull synocommunity
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'SynoCommunity'
          repository: 'spksrc'
          
      - name: Prepare build
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        run: cd spksrc/ && make setup

      - name: Cache 
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        uses: actions/cache@v4
        with:
          path: spksrc/distrib/toolchain
          key: 2
      
      - name: Update cloudflared version cross
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        run: sed -i "s/^PKG_VERS = [0-9]\+\.[0-9]\+\.[0-9]\+/PKG_VERS = ${{ steps.cloudflared-version.outputs.tag }}/" spksrc/cross/cloudflared/Makefile
      
      - name: Update cloudflared version spk
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        run: sed -i "s/^SPK_VERS = [0-9]\+\.[0-9]\+\.[0-9]\+/SPK_VERS = ${{ steps.cloudflared-version.outputs.tag }}/" spksrc/spk/cloudflared/Makefile

      - name: Bump cloudflared revision
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        run: sed -i -E 's/^(SPK_REV = )([0-9]+)/echo "\1$((\2 + 1))"/e' spksrc/spk/cloudflared/Makefile
        
      - name: Update digests
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        run: cd spksrc/cross/cloudflared && make digests
        
      - name: Build all-supported
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        run: cd spksrc/spk/cloudflared && make all-supported
        
      - name: Upload Artifact
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: spksrc/packages/*
          
  publish:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get latest cloudflared version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: cloudflare/cloudflared
          releases-only: true
        id: cloudflared-version

      - run: echo "cloudflared is at version ${{ steps.cloudflared-version.outputs.tag }}"

      - name: Get latest built version
        continue-on-error: true
        uses: oprypin/find-latest-tag@v1
        with:
          repository: paulgit/syno-cloudflared-builds
          releases-only: true
        id: syno-cloudflared-version
        
      - run: echo "syno-cloudflared is at version ${{ steps.syno-cloudflared-version.outputs.tag }}"

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
          
      - name: Calculate sha256
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        run: |
          {
            cd packages
            echo 'SUMS<<EOF'
            find . -type f -exec sha256sum {} \;
            echo EOF
          } >> "$GITHUB_OUTPUT"
        id: sha256

      - name: Print sha256
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        run: echo '${{ steps.sha256.outputs.SUMS }}'
          
      - name: Release
        if: steps.cloudflared-version.outputs.tag != steps.syno-cloudflared-version.outputs.tag
        uses: ncipollo/release-action@v1.20.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: packages/*
          tag: ${{ steps.cloudflared-version.outputs.tag }}
          immutableCreate: true
          body: ${{ steps.sha256.outputs.SUMS }}
